### ISSUE TITLE
L-curve will only run if make_graphs = 0

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/GRNmap#174]
As noted in issue #168, the L-curve will only run without error when make_graphs = 0 in the optimization_parameters worksheet.

When I attempted to run it with make_graphs = 1 on the full list of alphas, I got the following error:

javax.media.opengl.GLException: Unable to create temp OpenGL context for device context 0xffffffffeb0110a0
	at jogamp.opengl.windows.wgl.WindowsWGLContext.createImpl(WindowsWGLContext.java:312)
	at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:662)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:561)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:518)
	at javax.media.opengl.awt.GLJPanel$OffscreenBackend.initialize(GLJPanel.java:1466)
	at javax.media.opengl.awt.GLJPanel.initializeBackendImpl(GLJPanel.java:1148)
	at javax.media.opengl.awt.GLJPanel.paintComponent(GLJPanel.java:526)
	at com.mathworks.hg.peer.JavaSceneServerGLJPanel.paintComponent(JavaSceneServerGLJPanel.java:121)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at com.mathworks.hg.peer.FigureClientProxyPanel.paint(FigureClientProxyPanel.java:88)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.BufferStrategyPaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at java.awt.GraphicsCallback$PaintCallback.run(Unknown Source)
	at sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
	at sun.awt.SunGraphicsCallback.runComponents(Unknown Source)
	at java.awt.Container.paint(Unknown Source)
	at java.awt.Window.paint(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$700(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$200(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Error in alternatePrintPath (line 91)

Error in print (line 215)
    pj = alternatePrintPath(pj);

Error in graphs (line 60)
    print(filename,'-djpeg')

Error in output (line 21)
    GRNstruct = graphs(GRNstruct);

Error in GRNLCurve (line 68)
        GRNstruct = output(GRNstruct);

Error in GRNmodel (line 32)
   GRNstruct = GRNLCurve(GRNstruct);

This bug will need to be verified and eventually fixed.

**Comment by trixr4kdz** [comment]
@juansc and I have verified that this bug occurs when too many figures are created. One solution that we came up with is to "close all" the figures generated in each run so MATLAB is not overwhelmed with too many open figures. The other solution is to store all figures of each individual run in a separate output directory.

**Comment by kdahlquist** [comment]
I think we should adhere to what we have designed into the program:
* if make_graphs = 0, no expression graphs made or saved (but the optimization diagnostic is always saved)
* if make_graphs = 1, all expression graphs made and saved.  

The way @bengfitzpatrick is saving the output .xlsx workbooks is by appending an underscore followed by a number to the end of the file name, e.g., "_1", "_2", etc. which corresponds to the order of the runs.  It seems that if make_graphs = 1, then we could save the files with the gene name and _1, _2, etc.  Then the user decides whether they want to make and save all the graphs or not.

**Comment by juansc** [comment]
Now that I think about it (after getting some sleep) I think we can still save all the pictures and use `close all`. We would save all the expression graphs that are created during a run with a particular alpha, and then at the end of the run we close all the graphs. This would prevent the problem of having too many figures open at any given time, and all the expression graphs are preserved.

**Comment by kdahlquist** [comment]
That makes sense.

**Comment by juansc** [comment]
We attempted to reproduce the bug by creating 200 figures and saving them but we could not reproduce the error. We have yet to determine why this error occurs.

**Comment by dondi** [comment]
The error looks like there is a resource being used (the OpenGLContext) during graph generation when L-curves are being run which is not being released after the figure is generated. The original attempt at doing 200 figures might not have been replicating this clean up.

To isolate the bug, I suggest starting "at full capacity" (i.e., running as close to the same code as possible, including actually generating the figures, using the same data, etc.). Presumably you will see the error at that point. Then, whittle down little by little until you reach a point where the error does not come up. The combination of eliminated components should help lead to the root cause then solution.

**Comment by dondi** [comment]
This is the kind of activity where good, written notes is really valuable, because it can become very hard to keep track of the combinations of conditions and their corresponding results in your head.

**Comment by trixr4kdz** [comment]
@juansc and I have tried to insert a line in the code so that all the generated figure windows are closed before any new ones are generated and so far the run has not crashed yet. Right now, the L-curve analysis has been running for about 4 hours and is in the 13th alpha. We are using the 15-gene file that @dahlquist sent us, but we've removed one of the strains to try to cut down the running time.

**Comment by trixr4kdz** [comment]
Closing all the generated figures before running a new one seems to have fixed this problem. I will make a new issue concerning appending successive numbers to the end of the names of the figures as @kdahlquist described.

**Comment by kdahlquist** [comment]
I have confirmed that this now works with the file: dHAP4_15_gene_network_deletion_added_input_KD_20160126.xlsx with the optimization parameters:

L_curve =1
estimate_params =1
make_graphs =1
fix_P =1
fix_b=1
